Develop

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,7 +30,6 @@ on:
 
 env:
   PUPPET_VERSION: '~> 6'
-  FORGE_USER_AGENT: GitHubActions-ForgeReleng-Workflow/0.4.0 (Purpose/forge-ops-for-${{ github.event.repository.name }})
 
 jobs:
   releng-checks:
@@ -39,7 +38,6 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          ref: ${{ github.event.inputs.branch}}
           clean: true
       - uses: ruby/setup-ruby@v1
         with:
@@ -63,6 +61,20 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          clean: true
+      - name: Get tag info
+        id: tag-check
+        run: |
+          annotation="$(git for-each-ref "${GITHUB_REF}" --format='%(contents)')"
+          tag="${GITHUB_REF/refs\/tags\//}"
+          [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is nott a tag: ${GITHUB_REF}"; exit 1 ; }
+          echo "::set-output name=tag::${tag}"
+          echo "::set-output name=annotation:${annotation}"
+      - name: Fake release
+        run: |
+          echo "== LATEST TAG:  ${{ steps.tag-check.outputs.tag }}"
+          printf "== ANNOTATION:\n-------\n%s\n-------\n\n" "${{ steps.tag-check.outputs.annotation }}"
 ####      - name: Create Release
 ####        uses: actions/create-release@v1
 ####        ### id: create_release
@@ -70,7 +82,7 @@ jobs:
 ####          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ####        with:
 ####          tag_name: ${{ github.ref }}
-####          release_name: Release ${{ github.ref }}
+####          release_name: Release of ${{ github.ref }}
 ####          body: |
 ####            Changes in this Release
 ####            - First Change
@@ -85,27 +97,20 @@ jobs:
     runs-on: ubuntu-18.04
     env:
       PUPPETFORGE_API_TOKEN: ${{ secrets.PUPPETFORGE_API_TOKEN }}
+      FORGE_USER_AGENT: GitHubActions-ForgeReleng-Workflow/0.4.0 (Purpose/forge-ops-for-${{ github.event.repository.name }})
     steps:
-      - name: Check tag ref
-        id: tag-check
-        run: |
-          tag=${GITHUB_REF/refs\/tags\//}
-          ### [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is nott a tag: ${GITHUB_REF}"; exit 1 ; }
-          echo "::set-output name=tag::${tag}"
-          echo "::set-failed ::error message"
       - name: Checkout code
         uses: actions/checkout@v2
         with:
-          ref: ${{ steps.tag-check.outputs.tag }}
+          clean: true
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.5
           bundler-cache: true
-      - run: bundle exec rake metadata_lint
+      - run: Last-minute checks
+      - run: 'jq . metadata.json'
       - name: Build Puppet module
         run: bundle exec pdk build --force
-      - run: 'echo "== LATEST TAG:  ${{ steps.tag-check.outputs.tag }}"'
-      - run: 'jq . metadata.json'
       - name: Deploy to Puppet Forge
         run: 'echo curl -sS --fail -A "$FORGE_USER_AGENT" -H "Authorization: Bearer ${PUPPETFORGE_API_TOKEN}" -X POST -F "file=@$(find $PWD/pkg -name ''*.tar.gz'')" https://forgeapi.puppet.com/v3/releases'
 
