Develop

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -62,11 +62,17 @@ jobs:
       - name: Get tag info (${{github.ref}})
         id: tag-check
         run: |
-          annotation="$(git for-each-ref "${GITHUB_REF}" --format='%(contents)')"
           tag="${GITHUB_REF/refs\/tags\//}"
-          [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is nott a tag: ${GITHUB_REF}"; exit 1 ; }
+          annotation="$(git tag -l -n10000 "$tag")"
+          [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }
           echo "::set-output name=tag::${tag}"
           echo "::set-output name=annotation::${annotation}"
+          echo == attempt 1
+          git for-each-ref "$GITHUB_REF" --format='%(contents)' --count=1
+          echo
+          echo == attempt 2
+          git tag -l -n10000 "$tag"
+
       - name: Fake release
         run: |
           echo "== LATEST TAG:  ${{ steps.tag-check.outputs.tag }}"
