Update GHA workflows

diff --git a/.github/workflows/release_rpms.yml b/.github/workflows/release_rpms.yml
--- a/.github/workflows/release_rpms.yml
+++ b/.github/workflows/release_rpms.yml
@@ -109,18 +109,30 @@ jobs:
           rpm_file_paths: ${{ steps.build-and-sign-rpm.outputs.rpm_file_paths }}
           rpm_gpg_file: ${{ steps.build-and-sign-rpm.outputs.rpm_gpg_file }}
           upload_url: ${{ steps.release-api.outputs.assets_url }}
-          asset_path: ${{ steps.build-and-sign-rpm.outputs.rpm_file_path }}
-          asset_name: ${{ steps.build-and-sign-rpm.outputs.rpm_file_basename }}
           asset_content_type: application/octet-stream
         run: |
-          files=(${rpm_file_paths} "$rpm_gpg_file")
+          curl_cmd=(curl -X POST --data-binary --fail --silent --show-error \
+            --header "Accept: application/vnd.github.v3+json" \
+            --header "Authorization: token ${GITHUB_TOKEN:-default_content_to_cause_error}" \
+            "${file}" "${upload_url}"\
+          )
+          files=(${rpm_file_paths})
           echo "== files to upload (including GPG public key file) : ${#files[@]}"
+
+
+          upload_reponse_body="$("${curl_cmd[@]}?name=$(basename "$rpm_gpg_file")" --header application/pgp-keys)"
+          echo "$upload_reponse_body | jq ."
+
           for file in "${files[@]}"; do
             echo "-- $file"
             if [ ! -f "$file" ]; then
               printf '::error ::No file found at $file (got "%s")!\n' "$file"
               exit 88
             fi
+            rpm -qip "$file" || { echo '::error ::Error reading RPM info from $file'; exit 88; }
+            file_name="$(basename "$file")"
+            upload_reponse_body="$("${curl_cmd[@]}?name=$(basename "$rpm_gpg_file")" --header "Content-Type: ${asset_content_type}"
+            echo "$upload_reponse_body | jq ."
           done
 
           echo "assets url: ${{ steps.release-api.outputs.assets_url }}"
