Update GHA workflows (Mocked)

diff --git a/.github/workflows/release_rpms.yml b/.github/workflows/release_rpms.yml
--- a/.github/workflows/release_rpms.yml
+++ b/.github/workflows/release_rpms.yml
@@ -164,6 +164,7 @@ jobs:
             fi
             rpm -q --qf '%{NEVRA}' -p "$file" || { echo '::error ::Error reading RPM info from $file'; exit 88; }
             file_name="$(basename "$file")"
+            ###full_upload_url="${upload_url}?name=${file_name}&label=${file_name}"
             full_upload_url="${upload_url}?name=${file_name}&label=${file_name}"
             echo
             echo "== Uploading '$file' to $full_upload_url"
@@ -177,8 +178,13 @@ jobs:
 
           #echo "-- curl_cmd: '${curl_cmd[@]}'"
           rpm_gpg_file_name="$(basename "$rpm_gpg_file")"
-          full_upload_url="${upload_url}?name=${rpm_gpg_file_name}&label=${rpm_gpg_file_name}"
+          full_upload_url="${upload_url}?name=${rpm_gpg_file_name}"
+          full_upload_url="${upload_url}?name=${file_name}"
           echo
+          if [ ! -f "$rpm_gpg_file" ]; then
+            printf '::error ::No file found at $rpm_gpg_file (got "%s")!\n' "$rpm_gpg_file"
+            exit 88
+          fi
           echo "== Uploading '$rpm_gpg_file_name' to $full_upload_url == GPG =="
           gpg_upload_cmd=(
              "${curl_cmd[@]}" "$full_upload_url" \
