Test bump to 0.3.46

diff --git a/.github/workflows/tag_deploy.yml b/.github/workflows/tag_deploy.yml
--- a/.github/workflows/tag_deploy.yml
+++ b/.github/workflows/tag_deploy.yml
@@ -11,13 +11,14 @@
 #
 # This pipeline uses the following GitHub Action Secrets:
 #
-#   GitHub Secret variable           Type      Notes
-#   -------------------------------  --------  ---------------------------------
-#   PUPPETFORGE_API_TOKEN            Required
-#   SIMP_CORE_REF_FOR_BUILDING_RPMS  Required  simp-core ref (tag) to use to
-#                                              build RPMs with `rake pkg:single`
-#   SIMP_DEV_GPG_SIGNING_KEY         Required
-#   SIMP_DEV_GPG_SIGNING_KEY_ID      Required
+#   GitHub Secret variable               Notes
+#   -------------------------------      ---------------------------------------
+#   PUPPETFORGE_API_TOKEN
+#   SIMP_CORE_REF_FOR_BUILDING_RPMS      simp-core ref (tag) to use to build
+#                                        RPMs with `rake pkg:single`
+#   SIMP_DEV_GPG_SIGNING_KEY             GPG signing key's secret key
+#   SIMP_DEV_GPG_SIGNING_KEY_ID          User ID (name) of signing key
+#   SIMP_DEV_GPG_SIGNING_KEY_PASSPHRASE  Passphrase to use GPG signing key
 #
 # ------------------------------------------------------------------------------
 #
@@ -37,32 +38,32 @@ env:
   PUPPET_VERSION: '~> 6'
 
 jobs:
-###  releng-checks:
-###    name: "RELENG checks"
-###    if: github.repository_owner == 'simp'
-###    runs-on: ubuntu-18.04
-###    steps:
-###      - name: "Assert '${{ github.ref }}' is a tag"
-###        run: '[[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }'
-###      - uses: actions/checkout@v2
-###        with:
-###          ref: ${{ github.ref }}
-###          clean: true
-###      - uses: ruby/setup-ruby@v1
-###        with:
-###          ruby-version: 2.5
-###          bundler-cache: true
-###      - run: bundle exec rake pkg:check_version
-###      - run: bundle exec rake pkg:compare_latest_tag
-###      - run: bundle exec rake pkg:create_tag_changelog
-###      - run: bundle exec rake metadata_lint
-###      - name: "Test that Puppet module can build"
-###        run: "bundle exec pdk build --force"
+  releng-checks:
+    name: "RELENG checks"
+    if: github.repository_owner == 'simp'
+    runs-on: ubuntu-18.04
+    steps:
+      - name: "Assert '${{ github.ref }}' is a tag"
+        run: '[[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }'
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ github.ref }}
+          clean: true
+      - uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 2.5
+          bundler-cache: true
+      - run: bundle exec rake pkg:check_version
+      - run: bundle exec rake pkg:compare_latest_tag
+      - run: bundle exec rake pkg:create_tag_changelog
+      - run: bundle exec rake metadata_lint
+      - name: "Test that Puppet module can build"
+        run: "bundle exec pdk build --force"
 
 
   create-github-release:
     name: Deploy GitHub Release
-###    needs: [ releng-checks ]
+    needs: [ releng-checks ]
     if: github.repository_owner == 'simp'
     runs-on: ubuntu-18.04
     steps:
@@ -81,7 +82,6 @@ jobs:
           gpg_signing_key_id: ${{ secrets.SIMP_DEV_GPG_SIGNING_KEY_ID }}
           gpg_signing_key_passphrase: ${{ secrets.SIMP_DEV_GPG_SIGNING_KEY_PASSPHRASE }}
           simp_core_ref_for_building_rpms: ${{ secrets.SIMP_CORE_REF_FOR_BUILDING_RPMS }}
-
 
       - name: Get tag & annotation info (${{github.ref}})
         id: tag-check
